all:	doc tests

tests:
#	cd Resources/Test\ Data/Builder && make -j3
#	cd Resources/Test\ Data/Loader && make -j3

doc:	
	cd Resources/Doc && make -j3

clean:
#	cd Resources/Test\ Data/Builder && make clean
#	cd Resources/Test\ Data/Loader && make clean
	cd Resources/Doc && make clean
